namespace: demoapp-dev
bases:
- ../../base
patchesStrategicMerge:
- patch-deployments.yaml
- patch-services.yaml
resources:
- namespace.yaml
- ingress.yaml
configMapGenerator:
  - name: app-config
    envs:
      - config-dev.env
secretGenerator:
  - name: postgres-secret
    envs:
      - secret-dev.env
