namespace: demoapp-dev
bases:
- ../../base
patchesStrategicMerge:
- patch-deployments.yaml
- patch-services.yaml
resources:
- namespace.yaml
configMapGenerator:
  - name: app-config
    files:
      - config.env=config-dev.env
