apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-frontend
spec:
  template:
    spec:
      containers:
      - name: demoapp-frontend
        image: demoapp-frontend-dev
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-backend
spec:
  template:
    spec:
      containers:
      - name: demoapp-backend
        image: demoapp-backend-dev
        ports:
        - containerPort: 8080
