# Use Node.js for the development environment
FROM node:22.13-alpine3.20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn files) for dependencies
COPY package*.json ./

# Install development dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port (typically used by React development server)
EXPOSE 3000

# Use volume mounting to enable live code updates
VOLUME ["/app"]

# Run the development server (with hot-reloading)
CMD ["npm", "start"]
