services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: ${REGISTRY_PATH}/demoapp-frontend
    ports:
      - "${PROD_PORT}:80"
    environment:
      - REACT_APP_API_URL=${PROD_API_URL}
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: ${REGISTRY_PATH}/demoapp-backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - PORT=8080
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local